pipeline {
    agent any

    tools {
        nodejs '14.0.0'
    }
    stages {
        stage('Build') {
            steps {
                sh 'node --version'    
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}